steps:
  - name: Setup repo
    uses: actions/checkout@v4
    with:
      submodules: recursive
      fetch-depth: 0


      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

    - name: Verify submodule content
      run: |
        echo "Submodule status:"
        git submodule status
        echo "Monster-DB contents:"
        ls -la static/monster-hunter-DB/
        echo "Full file tree:"
        tree static/

  - name: Deploy to Deno Deploy
    uses: denoland/deployctl@v1
    with:
      project: monhan-api
      entrypoint: main.ts
      import-map: deno.json
      include: |
        static/monster-hunter-DB/**/*
        main.ts
        type.ts
        deno.json
