name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest  

    steps:
      - name: Setup repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
        
      - name: Build step
        run: "deno task build"
        
      - name: List contents to verify submodule
        run: |
          ls -la static/monster-hunter-DB/
        
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: monhan-api
          entrypoint: main.ts
          import-map: deno.json
          include: |
            static/monster-hunter-DB/
            main.ts
            type.ts


      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # - name: Verify formatting
      #   run: deno fmt --check

      # - name: Run linter
      #   run: deno lint

      # - name: Run tests
      #   run: deno test -A
      # - name: Run application
      #   run: deno run --allow-net --allow-read main.ts
